In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Retail_Dataset_Modified.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [4]:
print("Data Types:")
print(df.dtypes)

Data Types:
Store_ID                  object
Store_Name                object
Brand_Name                object
Store_Type                object
City                      object
City_Tier                 object
Product_Name              object
Category                  object
Sub_Category              object
Product_Stage             object
Quantity_Available        object
Units_Sold                object
Unit_Price                 int64
Cost_Price                 int64
Revenue                   object
Profit_Margin            float64
Average_Order_Value        int64
Inventory_Turnover       float64
Days_of_Stock              int64
Customer_Segment          object
Sales_Channel             object
Payment_Method            object
Supplier                  object
Supplier_Rating           object
Promotion_Type            object
Promotion_Impact         float64
Max_Discount_Offered       int64
Return_Rate              float64
Return_Reason             object
Customer_Satisfaction    float64
Online_Rating            float64
Review_Count               int64
Sales_Rep_Experience       int64
Sales_Rep_Rating         float64
Market_Share             float64
Competition_Level         object
Competitor_Count           int64
Brand_Loyalty            float64
Brand_Awareness          float64
Price_Competitiveness     object
Weather_Impact            object
Delivery_Time            float64
Shipping_Cost             object
Month                      int64
Year                       int64
Quarter                   object
Season                    object
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(11), int64(10), object(26)
memory usage: 1.9+ MB

In [6]:
df['Quantity_Available'] = pd.to_numeric(
    df['Quantity_Available'],
    errors='coerce'
)

In [7]:
print(df['Quantity_Available'].dtypes)

float64

In [8]:
df['Units_Sold'] = pd.to_numeric(
    df['Units_Sold'],
    errors='coerce'
)

print(df['Units_Sold'].dtypes)

float64

In [9]:
df['Revenue'] = pd.to_numeric(
    df['Revenue'],
    errors='coerce'
)

print(df['Revenue'].dtypes)

float64

In [10]:
df['Shipping_Cost'] = pd.to_numeric(
    df['Shipping_Cost'],
    errors='coerce'
)

print(df['Shipping_Cost'].dtypes)

float64

In [11]:
print(df[['Quantity_Available',
          'Units_Sold',
          'Revenue',
          'Shipping_Cost']].dtypes)

Quantity_Available    float64
Units_Sold            float64
Revenue               float64
Shipping_Cost         float64
dtype: object

In [12]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        8
Units_Sold                8
Unit_Price                0
Cost_Price                0
Revenue                  80
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             8
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [13]:
missing_cols = df.isnull().sum()
print(
    missing_cols[missing_cols > 0]
)

City                     62
Product_Name             73
Quantity_Available        8
Units_Sold                8
Revenue                  80
Supplier                 68
Customer_Satisfaction    77
Delivery_Time            60
Shipping_Cost             8
dtype: int64

In [14]:
df['City'].fillna(
    df['City'].mode()[0],
    inplace=True
)

/tmp/ipykernel_4875/290529194.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna(

In [15]:
df['Product_Name'].fillna(
    df['Product_Name'].mode()[0],
    inplace=True
)

/tmp/ipykernel_4875/519652800.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Product_Name'].fillna(

In [16]:
df['Quantity_Available'].fillna(
    df['Quantity_Available'].mean(),
    inplace=True
    )

/tmp/ipykernel_4875/191301782.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity_Available'].fillna(

In [17]:
df['Units_Sold'].fillna(
    df['Units_Sold'].mean(),
    inplace=True
    )

/tmp/ipykernel_4875/2236326260.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Units_Sold'].fillna(

In [18]:
df['Revenue'].fillna(
    df['Revenue'].mean(),
    inplace=True
    )

/tmp/ipykernel_4875/1417158233.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Revenue'].fillna(

In [19]:
df['Supplier'].fillna(
    df['Supplier'].mode()[0],
    inplace=True
    )

/tmp/ipykernel_4875/3028109213.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Supplier'].fillna(

In [20]:
df['Customer_Satisfaction'].fillna(
    df['Customer_Satisfaction'].mean(),
    inplace=True
    )

/tmp/ipykernel_4875/676674439.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Satisfaction'].fillna(

In [21]:
df['Delivery_Time'].fillna(
    df['Delivery_Time'].mean(),
    inplace=True
    )

/tmp/ipykernel_4875/3409184888.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Time'].fillna(

In [22]:
df['Shipping_Cost'].fillna(
    df['Shipping_Cost'].mean(),
    inplace=True
    )

/tmp/ipykernel_4875/3368913573.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Shipping_Cost'].fillna(

In [23]:
print(df.isnull().sum())

Store_ID                 0
Store_Name               0
Brand_Name               0
Store_Type               0
City                     0
City_Tier                0
Product_Name             0
Category                 0
Sub_Category             0
Product_Stage            0
Quantity_Available       0
Units_Sold               0
Unit_Price               0
Cost_Price               0
Revenue                  0
Profit_Margin            0
Average_Order_Value      0
Inventory_Turnover       0
Days_of_Stock            0
Customer_Segment         0
Sales_Channel            0
Payment_Method           0
Supplier                 0
Supplier_Rating          0
Promotion_Type           0
Promotion_Impact         0
Max_Discount_Offered     0
Return_Rate              0
Return_Reason            0
Customer_Satisfaction    0
Online_Rating            0
Review_Count             0
Sales_Rep_Experience     0
Sales_Rep_Rating         0
Market_Share             0
Competition_Level        0
Competitor_Count         0
Brand_Loyalty            0
Brand_Awareness          0
Price_Competitiveness    0
Weather_Impact           0
Delivery_Time            0
Shipping_Cost            0
Month                    0
Year                     0
Quarter                  0
Season                   0
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5171 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5171 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   float64
 11  Units_Sold             5171 non-null   float64
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5171 non-null   float64
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5171 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5171 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5171 non-null   float64
 42  Shipping_Cost          5171 non-null   float64
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(15), int64(10), object(22)
memory usage: 1.9+ MB

In [25]:
duplicates = df.duplicated().sum()

print(
    "Duplicate Records:",
    duplicates
)

Duplicate Records: 25

In [26]:
print(df.duplicated().value_counts())

False    5146
True       25
Name: count, dtype: int64

In [27]:
df = df.drop_duplicates()

In [28]:
print(df.shape)

(5146, 47)

In [29]:
print(
    "Remaining Duplicates:",
    df.duplicated().sum()
)

Remaining Duplicates: 0

In [30]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring